apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  RAILS_ENV: "production"
  RAILS_MAX_THREADS: "10"
  RAILS_SERVE_STATIC_FILES: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
type: Opaque
data:
  DATABASE_URL: "..."
  SECRET_KEY_BASE: "..."
  RABBITMQ_URL: "..."